camunda.bpm:
  client:
    base-url: http://localhost:8080/engine-rest
  database:
    type: h2
  default-serialization-format: application/json
  filter:
    create: All tasks
  generic-properties:
    properties:
      initializeTelemetry: true
      telemetryReporterActivate: true
  login:
    enabled: false
    user-id: demo
    create-if-absent: true
    random-password: true
  admin-user:
    id: demo
    password: demo
